name: a_hole_meter
description: A new Flutter project.

publish_to: "none"
version: 2.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.12.0
  firebase_ui_firestore: ^1.6.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.9
  go_router: 12.1.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  image_cropper: ^5.0.1
  image_downloader:
    git:
      url: https://github.com/VikasTailorbird/image_downloader
  # the annotation package containing @riverpod
  riverpod_annotation: 2.3.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0
  google_mlkit_commons:
    # path: /Users/fred/Flutter Pojects/a_hole_meter/packages/google_mlkit_commons
  google_mlkit_face_detection:
    path: /Users/fred/Flutter Pojects/a_hole_meter/packages/google_mlkit_face_detection

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  random_string: ^2.3.1
  flutter_lints: ^3.0.1
  # a tool for running code generators
  build_runner: 2.4.6
  # the code generator
  riverpod_generator: 2.3.6
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 2.3.4
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.5.6

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
    - assets/dad1.png
    - assets/glory_hole.png
